name: Docker Build and Test

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Build Docker image
      run: docker build -t hello-app .
    
    - name: Run Docker container
      run: docker run -d -p 5000:5000 --name test-app hello-app
    
    - name: Test the app
      run: |
        sleep 5
        curl http://localhost:5000
    
    - name: Show logs
      run: docker logs test-app
